<x-guest-layout>
	@include('sections.hero')
	@include('sections.fokus')
	@include('sections.prestasi')
	@include('sections.artikel')
	@include('sections.faq')
	@include('sections.contact')
	@include('sections.footer')
</x-guest-layout>
